
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Feb 11 09:55:57 COT 2015
//----------------------------------------------------

package ejerciociocupvero;

import java.io.*;
import java_cup.runtime.*;

/** CUP v0.11a beta 20060608 generated parser.
  * @version Wed Feb 11 09:55:57 COT 2015
  */
public class AnalizadorSintactico extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public AnalizadorSintactico() {super();}

  /** Constructor which sets the default scanner. */
  public AnalizadorSintactico(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public AnalizadorSintactico(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\010\000\002\002\004\000\002\002\004\000\002\002" +
    "\006\000\002\003\011\000\002\004\003\000\002\004\003" +
    "\000\002\004\003\000\002\004\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\022\000\004\010\004\001\002\000\004\012\013\001" +
    "\002\000\004\002\012\001\002\000\004\013\007\001\002" +
    "\000\006\002\001\010\004\001\002\000\004\013\011\001" +
    "\002\000\004\002\uffff\001\002\000\004\002\000\001\002" +
    "\000\004\014\014\001\002\000\012\004\017\005\021\006" +
    "\016\007\020\001\002\000\004\011\022\001\002\000\006" +
    "\011\ufffb\013\ufffb\001\002\000\006\011\ufffd\013\ufffd\001" +
    "\002\000\006\011\ufffa\013\ufffa\001\002\000\006\011\ufffc" +
    "\013\ufffc\001\002\000\004\014\023\001\002\000\012\004" +
    "\017\005\021\006\016\007\020\001\002\000\004\013\ufffe" +
    "\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\022\000\006\002\004\003\005\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\003\007" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\004\014\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\004\023" +
    "\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$AnalizadorSintactico$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$AnalizadorSintactico$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$AnalizadorSintactico$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}




      public void report_error(String message, Object info) {
        StringBuffer m = new StringBuffer("Error");
        System.out.println(info.toString());

    if("#0".equals(info.toString())){
          System.out.println("Sentencia incorrecta; o sentencia vacia o falta ; al final de la sentencia");
          
        }else{

          if("#1".equals(info.toString())){
          System.out.println("La sintaxis ingresada en incorrecta");
           
        }else{
           if("#2".equals(info.toString())){
          System.out.println("Error se esperaba una K (KILOMETROS), o me esta enviando un numero como string o revisar antes de K debe de ir un número");
          
        }else{
         if("#3".equals(info.toString())){
          System.out.println("Error se esperaba una M (METROS) , o me esta enviando un numero como string o revisar antes de M debe de ir un número");

        } else{
           if("#4".equals(info.toString())){
          System.out.println("Se esperaba una S (SEGUNDOS), o me esta enviando un numero como string o revisar antes de S debe de ir un número");
       
        }else{
          if("#5".equals(info.toString())){
          System.out.println("Se esperaba una H (HORA), o me esta enviando un numero como string o revisar antes y despues de H debe de ir un número");
           
        }else{
if("#6".equals(info.toString())){
          System.out.println("ID inválido");
           
        }else{
           if("#7".equals(info.toString())){
          System.out.println("Se esperaba un /");
          
        }else{
          if("#8".equals(info.toString())){
          System.out.println("Se esperaba un =");
          
       }else{
if("#9".equals(info.toString())){
          System.out.println("Estas finalizando con un ; y aun la expresión esta incompleta ");
           
        
       }else{
if("#10".equals(info.toString())){
          System.out.println("Tu expresion esta incompleta falta un = o /");
           
        }

       }
     }
        }
        }
        } 
        }
        }
        }
        }
        }


    if(info instanceof java_cup.runtime.Symbol) {
      java_cup.runtime.Symbol s=((java_cup.runtime.Symbol)info);
      /* Comprueba si el numero de línea es mayor o igual que cero */
      String linea="";
      String columna="";

      if(s.left >= 0) {

        linea=""+(s.left+1);
        m.append(" en linea "+(s.left+1));
        /*Comprueba si el numero de columna es mayoro igual que cero */
        if (s.right >= 0){
            columna=""+(s.right+1);
        }
            m.append(", y columna "+(s.right+1));
      }
      if (!linea.equals("")&&!columna.equals("")) {
  System.out.println("El error se ha detectado en la linea: "+linea+" y la columna: "+columna);
}

    }
    m.append(" : "+message);
    //System.err.println(m);
    }
  
public void report_fatal_error(String message, Object info) {
       	report_error(message, info);
		//System.exit(1);
    }

    public void conversion(String a, String b, int a1,int b1){
 
  double c;  
 c=a1/b1;
 
  System.out.print(" La Velocidad de:\n"+a1+" "+a+"/"+b1+""+b+"="+c+""+a+"/"+b+"\n"); 
 
}
        public static void main(String[] args) throws FileNotFoundException, Exception{
        try {
            AnalizadorSintactico asin = new AnalizadorSintactico(
                    new AnalizadorLexico( new FileReader(args[0])));
            Object result = asin.parse().value;
            System.out.println("\n*** Resultados finales ***"+result);
        } catch (NullPointerException ex) {
            System.out.println("Tenemos Problemas con la Sintaxis");
                   }
    }

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$AnalizadorSintactico$actions {
  private final AnalizadorSintactico parser;

  /** Constructor */
  CUP$AnalizadorSintactico$actions(AnalizadorSintactico parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$AnalizadorSintactico$do_action(
    int                        CUP$AnalizadorSintactico$act_num,
    java_cup.runtime.lr_parser CUP$AnalizadorSintactico$parser,
    java.util.Stack            CUP$AnalizadorSintactico$stack,
    int                        CUP$AnalizadorSintactico$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$AnalizadorSintactico$result;

      /* select the action based on the action number */
      switch (CUP$AnalizadorSintactico$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // unidad ::= HORA 
            {
              Object RESULT =null;
		int hleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()).left;
		int hright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()).right;
		Object h = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSintactico$stack.peek()).value;
		
              RESULT = h.toString();
            
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("unidad",2, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // unidad ::= SEGUNDOS 
            {
              Object RESULT =null;
		int sgleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()).left;
		int sgright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()).right;
		Object sg = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSintactico$stack.peek()).value;
		      RESULT = sg.toString();    
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("unidad",2, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // unidad ::= METROS 
            {
              Object RESULT =null;
		int mleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()).left;
		int mright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()).right;
		Object m = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSintactico$stack.peek()).value;
		
              RESULT = m.toString();
            
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("unidad",2, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // unidad ::= KILOMETROS 
            {
              Object RESULT =null;
		int kleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()).left;
		int kright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()).right;
		Object k = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSintactico$stack.peek()).value;
		
              RESULT = k.toString(); 
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("unidad",2, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // expresion ::= ID IGUAL NUMERO unidad DIV NUMERO unidad 
            {
              Object RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-4)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-4)).right;
		Integer n = (Integer)((java_cup.runtime.Symbol) CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-4)).value;
		int m1left = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-3)).left;
		int m1right = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-3)).right;
		Object m1 = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-3)).value;
		int n1left = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)).left;
		int n1right = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)).right;
		Integer n1 = (Integer)((java_cup.runtime.Symbol) CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)).value;
		int m2left = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()).left;
		int m2right = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()).right;
		Object m2 = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSintactico$stack.peek()).value;
		 parser.conversion(m1.toString(),m2.toString(),n.intValue(),n1.intValue());
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("expresion",1, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-6)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // lista ::= expresion PUNTOYCOMA expresion PUNTOYCOMA 
            {
              Object RESULT =null;
		 System.out.println("Sentencia correcta sin errores.");
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("lista",0, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-3)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= lista EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)).value;
		RESULT = start_val;
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$AnalizadorSintactico$parser.done_parsing();
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // lista ::= expresion PUNTOYCOMA 
            {
              Object RESULT =null;
		 System.out.println("Sentencia correcta sin errores.");
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("lista",0, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

