
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Feb 09 20:16:32 COT 2015
//----------------------------------------------------

package ejerciociocupvero;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int HORA = 5;
  public static final int KILOMETROS = 2;
  public static final int SEGUNDOS = 4;
  public static final int EOF = 0;
  public static final int METROS = 3;
  public static final int NUMERO = 10;
  public static final int DIV = 7;
  public static final int ID = 6;
  public static final int IGUAL = 8;
  public static final int error = 1;
  public static final int PUNTOYCOMA = 9;
}

